name: CI/CD para C# .NET
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Clonar el código
      uses: actions/checkout@v3
 
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
 
    - name: Restaurar dependencias
      run: dotnet restore
 
    - name: Compilar la solución
      run: dotnet build --configuration Release